import React from 'react';
import Head from 'next/head';

export default function HeadComponent() {
  return (
    <Head>
      <title>Personal blog with Nextjs</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
