import React from 'react'
import Homepage from '../container/Homepage/Homepage'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import { getAllPosts } from '../data/posts/get-all-posts'
import { FullPost } from '../domain/posts/post'


export type HomeProps = {
  posts: FullPost;
}

export default function Home({ posts }: HomeProps) {

  return (
    <div>
      <Head>
        <title>Personal blog with Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage posts={posts} />
    </div>

  )
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = await getAllPosts()
  return {
    props: { posts },
  }
}
