import { GetStaticProps } from 'next'
import Head from 'next/head'
import React from 'react'
import { getAllPosts } from '../data/posts/get-all-posts'
import { PostData } from '../domain/posts/post'

export type HomeProps = {
  posts: PostData[];
}

export default function Home({ posts }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Create Next App!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {posts.map((post) => (
            <h2 key={post.slug}>{post.title}</h2>
          ))}
        </div>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = await getAllPosts()
  return {
    props: { posts },
  }
}
